blueprint:
  name: "IKEA Bilresa Scroll Wheel – Brightness Control (Right & Left)"
  description: "Universal Brightness Control for IKEA Bilresa Scroll Wheel with separate configurations for right and left rotation"
  domain: automation
  input:
    scrollwheel_right_event_entity:
      name: "Scroll Wheel Event Entity – Right Rotation"
      description: "Event Entity of the Scroll Wheel for Right Rotation"
      selector:
        entity:
          domain: event

    scrollwheel_left_event_entity:
      name: "Scroll Wheel Event Entity – Left Rotation"
      description: "Event Entity of the Scroll Wheel for Left Rotation"
      selector:
        entity:
          domain: event

    target_light:
      name: "Target Light"
      description: "Light to be controlled"
      selector:
        entity:
          domain: light

    scroll_right_direction:
      name: "Action on Right Rotation"
      description: "What should happen on Right Rotation?"
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "brighten"
            - label: "Decrease Brightness"
              value: "dim"
      default: "brighten"

    scroll_left_direction:
      name: "Action on Left Rotation"
      description: "What should happen on Left Rotation?"
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "brighten"
            - label: "Decrease Brightness"
              value: "dim"
      default: "dim"

    brightness_per_step_right:
      name: "Brightness Per Step – Right (%)"
      default: 5
      selector:
        number:
          min: 1
          max: 20

    brightness_per_step_left:
      name: "Brightness Per Step – Left (%)"
      default: 5
      selector:
        number:
          min: 1
          max: 20

    startup_brightness_right:
      name: "Startup Brightness on Turn On – Right (%)"
      default: 20
      description: "Brightness in % at which the light is turned on upon Right Rotation"
      selector:
        number:
          min: 5
          max: 50

    startup_brightness_left:
      name: "Startup Brightness on Turn On – Left (%)"
      default: 20
      description: "Brightness in % at which the light is turned on upon Left Rotation"
      selector:
        number:
          min: 5
          max: 50

trigger:
  - platform: state
    entity_id: !input scrollwheel_right_event_entity
    id: "right_scroll"
  - platform: state
    entity_id: !input scrollwheel_left_event_entity
    id: "left_scroll"

action:
  - variables:
      is_right_scroll: "{{ trigger.id == 'right_scroll' }}"
      scroll_direction_right: !input scroll_right_direction
      scroll_direction_left: !input scroll_left_direction
      bright_step_right: !input brightness_per_step_right
      bright_step_left: !input brightness_per_step_left
      startup_bright_right: !input startup_brightness_right
      startup_bright_left: !input startup_brightness_left
      target_entity: !input target_light
      
      # Bestimme Richtung basierend auf Trigger
      direction: >-
        {% if is_right_scroll %}
          {{ 1 if scroll_direction_right == 'brighten' else -1 }}
        {% else %}
          {{ 1 if scroll_direction_left == 'brighten' else -1 }}
        {% endif %}
      
      # Bestimme Helligkeit pro Schritt
      bright_step: "{{ bright_step_right if is_right_scroll else bright_step_left }}"
      
      # Bestimme Startup-Helligkeit
      startup_bright: "{{ startup_bright_right if is_right_scroll else startup_bright_left }}"
      
      # Event-Typ extrahieren
      event_type_str: "{{ state_attr(trigger.entity_id, 'event_type') }}"
      
      # Press-Count berechnen
      press_count:
        "{{ trigger.to_state.attributes.totalNumberOfPressesCounted | int(1) }}"
      
      # Helligkeitsänderung berechnen
      brightness_change: "{{ (bright_step | int(5) * press_count | int(1) * direction) }}"
      
      # Status prüfen
      light_on: "{{ states(target_entity) == 'on' }}"
      current_brightness: "{{ (state_attr(target_entity, 'brightness') or 0) | int(0) }}"
      brightness_in_pct: "{{ ((current_brightness / 255) * 100) | round(1) }}"
      
      # Neue Helligkeit mit Clamp berechnen
      raw_brightness: "{{ (startup_bright | int(20)) + brightness_change }}"
      new_brightness: >-
        {% set b = raw_brightness | int %}
        {% if b < 10 %}
          10
        {% elif b > 100 %}
          100
        {% else %}
          {{ b }}
        {% endif %}
  
  - if:
      - condition: template
        value_template: "{{ light_on }}"
    then:
      # Licht ist AN – mit brightness_step_pct regeln
      - if:
          - condition: template
            value_template: "{{ press_count < 8 or direction > 0 }}"
        then:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_step_pct: "{{ brightness_change }}"
        #else:
          # Bei extremem Scroll → ausschalten
        #  - service: light.turn_off
        #    target:
        #      entity_id: !input target_light
    else:
      # Licht ist AUS
      - if:
          - condition: template
            value_template: "{{ direction > 0 }}"
        then:
          # Helligkeit erhöhen → Licht mit Startwert einschalten und dann anpassen
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_pct: "{{ new_brightness | int }}"
        else:
          # Helligkeit reduzieren → Licht bleibt aus
          - service: light.turn_off
            target:
              entity_id: !input target_light

mode: queued
max: 20
