blueprint:
  name: "IKEA Bilresa Scroll Wheel – Brightness Control (Right & Left)"
  description: "Universal Brightness Control for IKEA Bilresa Scroll Wheel with separate configurations for right and left rotation"
  domain: automation
  input:
    scrollwheel_right_event_entity:
      name: "Scroll Wheel Event Entity – Right Rotation"
      description: "Event Entity of the Scroll Wheel for Right Rotation"
      selector:
        entity:
          domain: event

    scrollwheel_left_event_entity:
      name: "Scroll Wheel Event Entity – Left Rotation"
      description: "Event Entity of the Scroll Wheel for Left Rotation"
      selector:
        entity:
          domain: event

    target_light:
      name: "Target Light"
      description: "Light to be controlled"
      selector:
        entity:
          domain: light

    scroll_right_direction:
      name: "Action on Right Rotation"
      description: "What should happen on Right Rotation?"
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "brighten"
            - label: "Decrease Brightness"
              value: "dim"
      default: "brighten"

    scroll_left_direction:
      name: "Action on Left Rotation"
      description: "What should happen on Left Rotation?"
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "brighten"
            - label: "Decrease Brightness"
              value: "dim"
      default: "dim"

    brightness_per_step_right:
      name: "Brightness Per Step – Right (%)"
      default: 5
      selector:
        number:
          min: 1
          max: 20

    brightness_per_step_left:
      name: "Brightness Per Step – Left (%)"
      default: 5
      selector:
        number:
          min: 1
          max: 20

    startup_brightness_right:
      name: "Startup Brightness on Turn On – Right (%)"
      default: 20
      description: "Brightness in % at which the light is turned on upon Right Rotation"
      selector:
        number:
          min: 5
          max: 50

    startup_brightness_left:
      name: "Startup Brightness on Turn On – Left (%)"
      default: 20
      description: "Brightness in % at which the light is turned on upon Left Rotation"
      selector:
        number:
          min: 5
          max: 50

trigger:
  - platform: state
    entity_id: !input scrollwheel_right_event_entity
    id: "right_scroll"
  - platform: state
    entity_id: !input scrollwheel_left_event_entity
    id: "left_scroll"
